Backend
aalmds/Amazona pull request #11
Opened 2023-03-22 14:19 UTC by KennedyMelo

## :memo: Summary

Describe the main changes and any relevant information.

## :white_check_mark: Type of change

- [x] Feature
- [ ] Refactor
- [ ] Bug fix

2023-03-27 02:03 UTC, victormarques-ia requested changes

2023-03-27 02:03 UTC, victormarques-ia commented on server/src/services/notification.service.ts
> +            const order = await this.orderService.getOrderById(notification.orderId);
It was not necessary return the full order data in this case. When the notification is received, it will only be necessary to have the orderId. Since it's already done, we can leave.

2023-03-27 02:03 UTC, victormarques-ia commented on server/src/services/order.service.ts
> +  public async updateOrderById(id: string, item: OrderStatusItemEntity): Promise<void> {
I think how this function specifically updates the order by adding a new status. I think it should have another name like addOrderStatusById.

updateOrderById, this for something more generic, refers to updating any Order information, which is not the case.

2023-03-27 02:03 UTC, victormarques-ia commented on server/src/controllers/order.controller.ts
> +    this.router.put(`${this.prefix}/:id`, (req: Request, res: Response) =>
If this endpoint is just waiting for an Order update that adds a new status, I think it should change to something like:

${this.prefix}/status/:id

${this.prefix}/:id => Refers to an update on any Order value, which is not the case, as it specifically expects a new status.

2023-03-27 02:03 UTC, victormarques-ia commented on server/src/controllers/order.controller.ts
> +  private async updateOrderById(req: Request, res: Response) {
If this function is just waiting for an Order update that adds a new status, I think it should change to something like:

addOrderStatusById

2023-03-30 22:34 UTC, victormarques-ia requested changes

2023-03-30 22:34 UTC, victormarques-ia commented on server/src/services/order.service.ts
> +  public async getHistoryByUserId(userId: string, historyId: any, productName: any, purchaseDate: any): Promise<OrderModel[]> {
Acho que acabou havendo um engano aqui, esse endpoint é para filtrar os pedidos, pelos historyId, productName, purchaseDate. Não para filtrar os produtos/historicos de um pedido.

Creio que o código seria algo assim:
* A função getAllOrderByUserId teria que ser implementada no OrderService, ela pegaria todos os pedidos de um usuário, algo parecido com o getOrderById (ou seja já retornando no formato de model).
```
public async getHistoryByUserId(userId: string, historyId: any, productName: any, purchaseDate: any): Promise<OrderModel[]> {
    try {
      const orders: OrderModel[] = await this.getAllOrderByUserId(userId);
      const results = await Promise.all(
        orders.map(async (order) => {
          try {
            let hasStatusHistory = false;
            let hasSomeProductWithName = false;
            let hasPurchaseDate = false;
  
            if (!!purchaseDate) {
              hasPurchaseDate = order.purchaseDate.toISOString() === purchaseDate;
            } else {
              hasPurchaseDate = true; // se não foi fornecido purchaseDate, assume-se que foi atendido
            }
  
            if (!!historyId) {
              hasStatusHistory = order.statusHistory.some((status) => status.id === historyId);
            } else {
              hasStatusHistory = true; // se não foi fornecido historyId, assume-se que foi atendido
            }
  
            if (!!productName) { 
              hasSomeProductWithName = order.products.some((product) => product.name.contains(productName));
            } else {
              hasSomeProductWithName = true; // se não foi fornecido productName, assume-se que foi atendido
            }
  
            if (hasStatusHistory && hasSomeProductWithName && hasPurchaseDate) {
              return order;
            }
  
          } catch (e) {
            logger.error(
              `[OrderService][getOrders] Error while processing order ${order.id}:`,
              e
            );
            return null;
          }
        })
      );
  
      const filteredResults = results.filter(
        (result) => !!result
      ) as OrderModel[];
  
      return filteredResults;
    } catch (e) {
      throw e;
    }
  }

```

2023-04-03 18:31 UTC, victormarques-ia commented on server/src/controllers/order.controller.ts
> +    let purchaseDate = req.query.purchaseDate
Change to two params.
- initialDate
- endDate

2023-04-03 18:31 UTC, victormarques-ia commented on server/src/controllers/order.controller.ts
> +    let historyId = req.query.historyId
Change to historiesStatus, this will be an array.

2023-04-03 18:31 UTC, victormarques-ia commented on server/src/services/order.service.ts
> +              hasStatusHistory = order.statusHistory.some((status) => status.id === historyId);
You can do, something like that:

hasStatusHistory = order.statusHistory.some((status) => historiesStatus.includes(status.name));

2023-04-03 18:31 UTC, victormarques-ia commented on server/src/services/order.service.ts
> +              hasPurchaseDate = order.purchaseDate.toISOString() === purchaseDate;
You will need to transform the initialDate and endDate received, to type Date. And then compare if the purchaseDate is >= inititalDate and <= endDate.

https://www.freecodecamp.org/news/javascript-date-comparison-how-to-compare-dates-in-js/

2023-04-04 18:31 UTC, aalmds approved these changes
Thinks that we can solve after the back integration:
1. Add a pattern, some findAll functions are creating a variable and then returning it latter, some others just make the return directly. 
2. Put all the message errors in English.

2023-04-04 21:17 UTC, victormarques-ia requested changes

2023-04-04 21:17 UTC, victormarques-ia commented on server/src/services/email.service.ts
> +    this.emailFrom = "amazona.ecommerce3@gmail.com";
It's better and more safety put these values ​​on .env.

2023-04-04 21:17 UTC, victormarques-ia commented on server/src/services/email.service.ts
> +        console.log(error);
Use logger.

2023-04-04 21:17 UTC, victormarques-ia commented on server/src/services/notification.service.ts
> +      await email.sendEmail("kennedycmelo@gmail.com", data.title, data.description)
I think that you can use the amazona.ecommerce3@gmail.com value here also.

2023-04-04 21:39 UTC, aalmds commented on server/src/services/order.service.ts
> +  public async getHistoryByUserId(userId: string, historiesStatus: any, productName: any, initialDate: any, endDate: any): Promise<OrderModel[]> {
Refactor this method, the conditionals are too nested.

2023-04-04 21:41 UTC, aalmds commented on server/src/services/order.service.ts
> +      } else{
This else is not needed because of the exception,

2023-04-04 21:43 UTC, aalmds commented on server/src/services/order.service.ts
> +          title: `Criação do pedido de número X com sucesso`,
Maybe we could define a place (utils?) to put the strings as constants.

2023-04-06 00:57 UTC, merged