feat(shared): create button component
aalmds/Amazona pull request #12
Opened 2023-03-23 21:55 UTC by mariavmuniz

## :memo: Summary

Create button component and style with parameters.

## :white_check_mark: Type of change

- [x] Feature
- [ ] Refactor
- [ ] Bug fix

2023-03-25 13:37 UTC, victormarques-ia requested changes

2023-03-25 13:37 UTC, victormarques-ia commented on web-app/src/app/shared/button/button.component.ts
It is necessary that the button component can receive a function by parameter, and then this function would be called from the onClick function.

Just missing that, good job!

2023-03-27 00:57 UTC, mariavmuniz commented on web-app/src/app/shared/button/button.component.ts
Resolved

2023-03-27 02:05 UTC, victormarques-ia approved these changes

2023-03-27 22:36 UTC, victormarques-ia approved these changes

2023-03-28 02:59 UTC, aalmds approved these changes

2023-03-28 02:59 UTC, merged