style(shared): created card component
aalmds/Amazona pull request #16
Opened 2023-03-28 02:42 UTC by jmarcossss

## :memo: Summary

Describe the main changes and any relevant information.

## :white_check_mark: Type of change

- [x] Feature
- [ ] Refactor
- [ ] Bug fix

2023-03-29 17:56 UTC, victormarques-ia requested changes
O app-card ficaria dessa forma, o ng-content  é uma diretiva que recebe o conteudo dentro de um component e o exibe.

https://angular.io/guide/content-projection

<img width="1048" alt="Captura de Tela 2023-03-29 às 14 42 55" src="https://user-images.githubusercontent.com/60486864/228623275-714b4b23-f086-45f5-a6fa-71a70c32924d.png">

O uso fica dessa forma, não precisamos passar atributos. É literalmente apenas o corpo do card.
<img width="1048" alt="Captura de Tela 2023-03-29 às 14 53 26" src="https://user-images.githubusercontent.com/60486864/228625750-a5be8d59-765f-4b17-8874-dd8fcac07829.png">
O card.componente.ts fica dessa forma.
<img width="1044" alt="Captura de Tela 2023-03-29 às 14 55 20" src="https://user-images.githubusercontent.com/60486864/228626226-f07b4b6c-9060-4012-ae8f-4f02004d256e.png">



O resultado é esse. Lembre de usar as variaveis de cores que estão no styles.css
<img width="1440" alt="Captura de Tela 2023-03-29 às 14 54 13" src="https://user-images.githubusercontent.com/60486864/228625951-e7d7c6a9-56d7-44f3-9748-f9410924e2a5.png">

*Lembre de remover os comentários*

2023-03-29 21:23 UTC, victormarques-ia requested changes
- O componente card não precisa ter nenhuma personalização que influencie visualmente o que vai ser passado para dentro dele, como por exemplo: margin, padding, etc. Dessa forma, conseguimos reaproveitar ele em mais lugares.
- Creio que o modulo card-black pode ser removido!

2023-03-29 21:23 UTC, victormarques-ia commented on web-app/src/app/shared/card/card.component.css
> +.card-image {
Ainda necessita dessa class ?

2023-03-29 21:23 UTC, victormarques-ia commented on web-app/src/app/shared/card/card.component.css
> +.card {
O card é apenas o corpo, ou seja, apenas precisa ter o border radius, a cor do background  e o box-shadow. Além disso, é importante utilizar as variáveis que estão no arquivos styles.css. Por exemplo, la tem o --color-cards que é a cor de background do card.

background-color: var(--color-cards);

2023-03-29 21:23 UTC, victormarques-ia commented on web-app/src/assets/images/roupa.jpeg
Essa imagem não é necessária

2023-03-30 11:36 UTC, victormarques-ia requested changes

2023-03-30 11:36 UTC, victormarques-ia commented on web-app/src/assets/images/cart-outline.svg
Para o que estaria sendo usado esses svgs ? a gente tá utilizando os ícones do Material, já para não precisar adicionar ícones/svgs no projeto.

2023-03-30 21:45 UTC, victormarques-ia approved these changes

2023-04-01 21:11 UTC, aalmds approved these changes

2023-04-01 21:11 UTC, merged