feat(adm): adding feature for the admin page
aalmds/Amazona pull request #8
Opened 2023-03-17 21:54 UTC by Raafm

## :memo: Summary
adding feature with 4  scenario for the admin page

## :white_check_mark: Type of change

- [ x] Feature
- [ ] Refactor
- [ ] Bug fix

2023-03-18 21:09 UTC, aalmds requested changes

2023-03-18 21:09 UTC, aalmds commented on features/calculateTotalPurchase.feature
> +
Missing As a ... I want to ... So that ...

2023-03-18 21:09 UTC, aalmds commented on features/calculateTotalPurchase.feature
> +        And o usuário está na página de administrador
```suggestion
        Given que o usuário com CPF “00000000013” está na página de "administrador"
```

2023-03-18 21:09 UTC, aalmds commented on features/calculateTotalPurchase.feature
> +        And o usuário está na página de administrador
```suggestion
        Given que o usuário com CPF “00000000013” está na página de "administrador"

```

2023-03-18 21:09 UTC, aalmds commented on features/calculateTotalPurchase.feature
> +        When  O usuário acessa a aba de dados por pedido (ID 130)
```suggestion
        When  o usuário de CPF "00000000013" acessa os "dados por pedido"
```

2023-03-18 21:09 UTC, aalmds commented on features/calculateTotalPurchase.feature
> +        And O usuário acessa a aba de dados por pedido (ID 132)
```suggestion
        Given que o usuário com CPF “00000000013” está na página de "administrador"
        When o usuário de CPF "00000000013" seleciona o período "mês"
        And o usuário de CPF "00000000013"  acessa os "dados por pedido"
```

2023-03-18 21:09 UTC, aalmds commented on features/calculateTotalPurchase.feature
> +        When  O usuário acessa a aba de dados para pedidos cancelados (ID 131)
```suggestion
        When o usuário  de CPF "00000000013" acessa as dados para "pedidos cancelados"
```

2023-03-21 00:35 UTC, acrucha requested changes

2023-03-21 00:35 UTC, acrucha commented on features/calculateTotalPurchase.feature
> +        And A média, o máximo e o mínimo do valores das compras (no tempo) são respectivamente "15000", "20000" e "10000"
Just to make it easier to understand, you can replace it with:

```
And as métricas de valores "dos pedidos no tempo" são "15000" para "média", "20000" para "valor máximo" e "10000" para "valor mínimo"
```

2023-03-21 00:35 UTC, acrucha commented on features/calculateTotalPurchase.feature
> +        Then os valores  "15000", "20000" e "10000" que são, respectivamente, a média, o máximo e o mínimo do valor das compras (no tempo) são mostrados
Also:

```
And as métricas de valores "dos pedidos no tempo" mostradas são "15000" para "média", "20000" para "valor máximo" e "10000" para "valor mínimo"
```

2023-03-21 00:35 UTC, acrucha commented on features/calculateTotalPurchase.feature
> +        And A média, o máximo e o mínimo do valores das compras (por pedido) são respectivamente "150", "200" e "100"
As I suggested before:
```
And as métricas de valores "por pedido" são "150" para "média", "200" para "valor máximo" e "100" para "valor mínimo"
```

2023-03-21 00:35 UTC, acrucha commented on features/calculateTotalPurchase.feature
> +        Then os valores "150", "200" e "100" que são, respectivamente, a média, o máximo e o mínimo dos valores das compras em cada pedidos são mostrados
```
Then as métricas de valores "por pedido" mostradas são "150" para "média", "200" para "valor máximo" e "100" para "valor mínimo"
```

2023-03-21 00:35 UTC, acrucha commented on features/calculateTotalPurchase.feature
> +        And A média, o máximo e o mínimo do valores das compras canceladas (por pedido) são respectivamente "150", "200" e "100"
You need to adjust this step to be in the same format as the others that I commented before. You just need to copy the new step format and change the statistics type (in this case, "de pedidos cancelados").

2023-03-21 00:35 UTC, acrucha commented on features/calculateTotalPurchase.feature
> +        Then os valores "150", "200" e "100" que são, respectivamente, a média, o máximo e o mínimo dos valores das compras canceladas por pedido são mostrados
```
Then as métricas de valores "de pedidos cancelados" mostradas são "150" para "média", "200" para "valor máximo" e "100" para "valor mínimo"
```

2023-03-21 00:35 UTC, acrucha commented on features/calculateTotalPurchase.feature
> +        Then os valores "150", "200" e "100" que são, respectivamente, a média, o máximo e o mínimo dos valores das compras em cada pedidos no mês atual são mostrados
```
Then as métricas de valores "por pedido" mostradas são "150" para "média", "200" para "valor máximo" e "100" para "valor mínimo"
And o período selecionado é "mês"
```

2023-03-21 00:35 UTC, acrucha commented on features/calculateTotalPurchase.feature
> +        And A média, o máximo e o mínimo do valores das compras (no tempo) são respectivamente "15000", "20000" e "10000"
I chose the word "métricas" to refer to the statistics values, but you can choose another word. If you choose a different word, please remember to use it in all scenarios. All steps of this type must be identical, with the only difference being the parameters (the strings you passed such as "15000", "média", "valor máximo"...)

2023-03-21 00:35 UTC, acrucha commented on features/calculateTotalPurchase.feature
> +        And A média, o máximo e o mínimo do valores das compras (no tempo) são respectivamente "15000", "20000" e "10000"
When it comes to verifying that these values are correct, you can make a request to the backend. You can use [this](https://docs.cypress.io/api/commands/request) to receive the data in Cypress (test framework).

2023-03-21 00:35 UTC, acrucha commented on features/calculateTotalPurchase.feature
> +        And A média, o máximo e o mínimo do valores das compras (no tempo) são respectivamente "15000", "20000" e "10000"
If you have any doubts, you can always send me a message, and I will get back to you as soon as possible.

2023-04-10 12:49 UTC, Raafm reviewed
fix(adm): name stats metrics

2023-04-12 02:59 UTC, closed without merging